Main/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.conf.urls import url
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from . import views

app_name = "Main"

urlpatterns = [
    path("password-reset/", 
        PasswordResetView.as_view(template_name="password_reset/password_reset_form.html",
                                  email_template_name="password_reset/password_reset_email.html",
                                  success_url=reverse_lazy('Main:password_reset_done')),
        name="password_reset"),
    
    
    path("password-reset/done/", 
         PasswordResetDoneView.as_view(template_name="password_reset/password_reset_done.html"),
         name="password_reset_done"),
    
    
    path("password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy('Main:password_reset_complete')
        ),
        name="password_reset_confirm"),
    
    path("password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete"),
    
    path("", views.home_page, name="home_page"),
    path("logout/", views.logout_page, name="log_out"),
    path("login/", views.login_page, name="login_page"),
    path("register/", views.register_page, name="register_page"),
    path("settings/", views.settings_page, name="settings_page"),
    path("notifications/", views.notifications_page, name="notifications_page"),
    path("notifications/<action>/", views.notifications__read_delete, name="notifications__read_delete"),
    path("notifications/<notification_id>/read/", views.notification_read, name="notification_read"),
    path("search/", views.search_page, name="search_page"),
    path("create-quiz/", views.create_quiz_page, name="create_quiz_page"),
    path("<user_slug>/", views.user_profile, name="user_profile"),
    path("<user_slug>/quizzes/", views.user_quizzes, name="user_quizzes"),
    path("<user_slug>/social/", views.user_social, name="user_social"),
    path("<user_slug>/action/<action>/", views.user_action, name="user_action"),
    path("<user_slug>/<quiz_slug>/", views.quiz_page, name="quiz_page"),
    path("<user_slug>/<quiz_slug>/edit/", views.edit_quiz_slug, name="edit_quiz_slug"),
    path("<user_slug>/<quiz_slug>/delete/", views.delete_quiz_slug, name="delete_quiz_slug"),
    url(r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.activate, name='activate'),
]

Spuiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

handler404 = "Main.views.handler404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce', include('tinymce.urls')),
    path('', include('Main.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/views.py
import json
import random
from django.db.models import Q
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.http.response import HttpResponse
from django.db.models import Count
from django.utils.text import slugify
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from .models import *
from .forms import *
from .tokens import account_activation_token
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.urls import reverse

def error_msg_response(request):
    data = {
            "msg": render_to_string(
                "static_html/messages.html",
                {
                    "messages": messages.get_messages(request),
                },
            ),
        }
                
    response = HttpResponse(
        json.dumps(data),
        content_type="application/json",
    )
    response.status_code = 218
    return response

def follow_unfollow_success_response(request, user_slug):
    
    user = UserProfile.objects.get(slug=user_slug).user
    followings = user.user_profile.following.order_by("username")
    completed_quizzes = CompletedQuiz.objects.filter(
        user__user_profile__slug=user_slug
    ).order_by("-completed_date")

    data = {
            "msg": render_to_string(
                "static_html/messages.html",
                {
                    "messages": messages.get_messages(request),
                },
            ),
            "new_page": render_to_string(
                "user_profile.html",
                context={
                    "viewing_user": user,
                    "followings": followings,
                    "completed_quizzes": completed_quizzes,
                },
                request=request
            )
        }
                
    response = HttpResponse(
        json.dumps(data),
        content_type="application/json",
    )
    response.status_code = 200
    return response


def calculate_rating(quiz):
    
    upvotes = quiz.upvotes.count()
    downvotes = quiz.downvotes.count()
    
    if (upvotes + downvotes) == 0:
        return [0, 5]
    
    fraction = round(upvotes / (upvotes + downvotes), 1)
    
    if fraction < 0.1:
        stars = 0
    elif fraction >= 0.1 and fraction < 0.3:
        stars = 1
    elif fraction >= 0.3 and fraction < 0.5:
        stars = 2
    elif fraction >= 0.5 and fraction < 0.7:
        stars = 3
    elif fraction >= 0.7 and fraction < 0.9:
        stars = 4
    elif fraction >= 0.9:
        stars = 5
        
    remainder = 5 - stars

    return [stars, remainder]

def calculate_percentage_score(score, total_score):
    return round((score / total_score) * 100, 1)

# Create your views here.
def home_page(request):
    newest_quizzes = Quiz.objects.all().order_by("-pk")[:10]
    top_quizzes = Quiz.objects.annotate(up_count=Count("upvotes")).order_by("-up_count")[:10]
    return render(request, "homepage.html", context={"newest_quizzes": newest_quizzes, 
                                                     "top_quizzes": top_quizzes})

def login_page(request):
        
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            
            if user is not None:
                msg = "You have successfully logged in."
                messages.success(request, msg)
                login(request, user)
                
                response = HttpResponse(msg)
                response.status_code = 200
                return response
            else:
                for msg in form.error_messages:
                    messages.error(request, f"{msg.upper()}: {form.error_messages[msg]}")
                
                response = {
                            "msg": render_to_string(
                                "static_html/messages.html",
                                {
                                    "messages": messages.get_messages(request),
                                },
                            ),
                        }
                        
            res =  HttpResponse(
                json.dumps(response),
                content_type="application/json",
            )
            res.status_code = 218
        
            return res
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg.upper()}: {form.error_messages[msg]}")
                
            return error_msg_response(request)
        
    if request.user.is_authenticated:
        return redirect("Main:home_page")
    
    form = LoginForm()
    return render(request,"login.html", context={"form": form})

def register_page(request):
    
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            
            message = render_to_string("activate_account_email.html", {
                "user": user,
                "domain": request.META["HTTP_HOST"],
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            })
            
            mail_subject = "Activate your Spuiz Account."
            to_email = form.cleaned_data.get("email")
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            
            msg = "Please confirm your email address to complete the registration"
            messages.info(request, msg)
        
            response = HttpResponse(msg)
            response.status_code = 200
            return response
        else:

            errors = json.loads(form.errors.as_json())

            for msg in errors:
                
                error_msg = errors[msg][0]["message"]
                
                if errors[msg][0]["code"] != "":
                    error_msg = errors[msg][0]["code"].upper() + ": " + error_msg
                    
                messages.error(request, error_msg)
                
            return error_msg_response(request)
        
    if request.user.is_authenticated:
        return redirect("Main:home_page")
    
    form = RegistrationForm()
    return render(request, "register.html", context={"form": form})
    
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "You have confirmed your email and have now been logged in")
        return redirect("Main:home_page")
    else:
        return HttpResponse("Activation link is invalid")

def logout_page(request):
    logout(request)
    messages.info(request, "You have been logged out.")
    return HttpResponseRedirect(request.GET.get("next", "/"))

def settings_page(request):
    
    if not request.user.is_authenticated:
        return redirect("Main:home_page")
    
    if request.method == "POST":
        
        user_profile = request.user.user_profile
        
        if "bio" in list(request.POST.keys()):
            
            user_profile.bio = request.POST["bio"]
            user_profile.save()
            
            messages.success(request, "Your biography has been successfully updated.")
        
        elif "avatar" in list(request.FILES.keys()):
            
            user_profile.avatar = request.FILES["avatar"]
            user_profile.save()
            
            messages.success(request, "Your avatar has been successfully updated.")
        
        elif "banner" in list(request.FILES.keys()):
            
            user_profile.banner = request.FILES["banner"]
            user_profile.save()
            
            messages.success(request, "Your banner has been successfully updated.")
                    
        else:
            form = UserEditForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, "Your account information has been successfully updated.")
            else:
                # messages.error(request, "An error has occurred while trying to save your account information.")
                errors = json.loads(form.errors.as_json())

                for msg in errors:
                    
                    error_msg = errors[msg][0]["message"]
                    
                    if errors[msg][0]["code"] != "":
                        error_msg = errors[msg][0]["code"].upper() + ": " + error_msg
                        
                    messages.error(request, error_msg)
                 
                data = {
                        "msg": render_to_string(
                            "static_html/messages.html",
                            {
                                "messages": messages.get_messages(request),
                            },
                        )
                    }
                            

Main/templates/password_reset/password_reset_complete.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/password_reset/password_reset_complete.css' %}">{% endblock %}
{% block title %}Reset Password{% endblock %}

{% block content %}

    <section id="reset_password_complete">
        <div class="card">
            <h2>Password reset complete</h2>
            <p>Your password has been set. You may go ahead and <a href="{% url "Main:login_page" %}">log in</a> now.</p>
        </div>
    </section>
{% endblock %}

Main/templates/password_reset/password_reset_confirm.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/password_reset/password_reset_confirm.css' %}">{% endblock %}
{% block title %}Reset Password{% endblock %}

{% block content %}

    <section id="reset_password_confirm">

        {% if validlink %}
        <form method="post" class="reset_password_form">
            <div class="info-text">
                <h2>Set new password</h2>
            </div>

            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Save</button>
        </form>
        {% else %}
        <div class="card">
            <h2>Invalid token.</h2>
            <p class="card-text">
                <a href="{% url "Main:password_reset" %}">Request a new password reset token</a>
            </p>
        </div>
        {% endif %}

    </section>
{% endblock %}

Main/templates/password_reset/password_reset_done.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/password_reset/password_reset_done.css' %}">{% endblock %}
{% block title %}Reset Password{% endblock %}

{% block content %}
    <section id="password_reset_done">
        <div class="card">
            <h2>Reset your password</h2>
            <p>We've emailed you instructions for setting your password, if an account exists with the email you entered.
                You should receive them shortly.</p>
            <p>If you don't receive an email, please make sure you've entered the address you registered with, and check
                your spam folder.</p>
            <p>Entered the wrong email? <a href="{% url 'Main:password_reset' %}">Retry here</a></p>
        </div>
    </section>
{% endblock %}

Main/templates/password_reset/password_reset_email.html
Hi, {{ user.username }}

You're receiving this email because you requested a password reset for your user account.
If this was not you, please ignore this email

Please open the link below to set a new password:
{{ protocol }}://{{ domain }}{% url "Main:password_reset_confirm" uidb64=uid token=token %}

Thanks,
Spimy - Founder of Spuiz.

Main/templates/password_reset/password_reset_form.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/password_reset/password_reset_form.css' %}">{% endblock %}
{% block title %}Reset Password{% endblock %}

{% block content %}
  <section id="reset_password">

        <form method="post" class="reset_password_form">

            <div class="info-text">
                <h2>Reset your password</h2>
            </div>

            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Send confirmation link</button>
        </form>

  </section>
{% endblock %}