Main/urls.py
from django.contrib import admin
from django.urls import path, reverse_lazy
from django.conf.urls import url
from django.contrib.auth.views import (PasswordResetView,
                                       PasswordResetDoneView,
                                       PasswordResetConfirmView,
                                       PasswordResetCompleteView)

from . import views

app_name = "Main"

urlpatterns = [
    path("password-reset/", 
        PasswordResetView.as_view(template_name="password_reset/password_reset_form.html",
                                  email_template_name="password_reset/password_reset_email.html",
                                  success_url=reverse_lazy('Main:password_reset_done')),
        name="password_reset"),
    
    
    path("password-reset/done/", 
         PasswordResetDoneView.as_view(template_name="password_reset/password_reset_done.html"),
         name="password_reset_done"),
    
    
    path("password-reset-confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="password_reset/password_reset_confirm.html",
            success_url=reverse_lazy('Main:password_reset_complete')
        ),
        name="password_reset_confirm"),
    
    path("password-reset-complete/",
        PasswordResetCompleteView.as_view(
            template_name="password_reset/password_reset_complete.html"
        ),
        name="password_reset_complete"),
    
    path("", views.home_page, name="home_page"),
    path("logout/", views.logout_page, name="log_out"),
    path("login/", views.login_page, name="login_page"),
    path("register/", views.register_page, name="register_page"),
    path("settings/", views.settings_page, name="settings_page"),
    path("notifications/", views.notifications_page, name="notifications_page"),
    path("notifications/<action>/", views.notifications__read_delete, name="notifications__read_delete"),
    path("notifications/<notification_id>/read/", views.notification_read, name="notification_read"),
    path("search/", views.search_page, name="search_page"),
    path("create-quiz/", views.create_quiz_page, name="create_quiz_page"),
    path("<user_slug>/", views.user_profile, name="user_profile"),
    path("<user_slug>/quizzes/", views.user_quizzes, name="user_quizzes"),
    path("<user_slug>/social/", views.user_social, name="user_social"),
    path("<user_slug>/action/<action>/", views.user_action, name="user_action"),
    path("<user_slug>/<quiz_slug>/", views.quiz_page, name="quiz_page"),
    path("<user_slug>/<quiz_slug>/edit/", views.edit_quiz_slug, name="edit_quiz_slug"),
    path("<user_slug>/<quiz_slug>/delete/", views.delete_quiz_slug, name="delete_quiz_slug"),
    url(r"^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$",
        views.activate, name='activate'),
]

Spuiz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve

handler404 = "Main.views.handler404"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce', include('tinymce.urls')),
    path('', include('Main.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Main/views.py
import json
import random
from django.db.models import Q
from django.contrib import messages
from django.http import Http404, HttpResponseRedirect, JsonResponse
from django.http.response import HttpResponse
from django.db.models import Count
from django.utils.text import slugify
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth.models import User
from django.core.mail import EmailMessage

from .models import *
from .forms import *
from .tokens import account_activation_token
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.urls import reverse

def error_msg_response(request):
    data = {
            "msg": render_to_string(
                "static_html/messages.html",
                {
                    "messages": messages.get_messages(request),
                },
            ),
        }
                
    response = HttpResponse(
        json.dumps(data),
        content_type="application/json",
    )
    response.status_code = 218
    return response

def follow_unfollow_success_response(request, user_slug):
    
    user = UserProfile.objects.get(slug=user_slug).user
    followings = user.user_profile.following.order_by("username")
    completed_quizzes = CompletedQuiz.objects.filter(
        user__user_profile__slug=user_slug
    ).order_by("-completed_date")

    data = {
            "msg": render_to_string(
                "static_html/messages.html",
                {
                    "messages": messages.get_messages(request),
                },
            ),
            "new_page": render_to_string(
                "user_profile.html",
                context={
                    "viewing_user": user,
                    "followings": followings,
                    "completed_quizzes": completed_quizzes,
                },
                request=request
            )
        }
                
    response = HttpResponse(
        json.dumps(data),
        content_type="application/json",
    )
    response.status_code = 200
    return response


def calculate_rating(quiz):
    
    upvotes = quiz.upvotes.count()
    downvotes = quiz.downvotes.count()
    
    if (upvotes + downvotes) == 0:
        return [0, 5]
    
    fraction = round(upvotes / (upvotes + downvotes), 1)
    
    if fraction < 0.1:
        stars = 0
    elif fraction >= 0.1 and fraction < 0.3:
        stars = 1
    elif fraction >= 0.3 and fraction < 0.5:
        stars = 2
    elif fraction >= 0.5 and fraction < 0.7:
        stars = 3
    elif fraction >= 0.7 and fraction < 0.9:
        stars = 4
    elif fraction >= 0.9:
        stars = 5
        
    remainder = 5 - stars

    return [stars, remainder]

def calculate_percentage_score(score, total_score):
    return round((score / total_score) * 100, 1)

# Create your views here.
def home_page(request):
    newest_quizzes = Quiz.objects.all().order_by("-pk")[:10]
    top_quizzes = Quiz.objects.annotate(up_count=Count("upvotes")).order_by("-up_count")[:10]
    return render(request, "homepage.html", context={"newest_quizzes": newest_quizzes, 
                                                     "top_quizzes": top_quizzes})

def login_page(request):
        
    if request.method == "POST":
        form = LoginForm(request, data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            
            if user is not None:
                msg = "You have successfully logged in."
                messages.success(request, msg)
                login(request, user)
                
                response = HttpResponse(msg)
                response.status_code = 200
                return response
            else:
                for msg in form.error_messages:
                    messages.error(request, f"{msg.upper()}: {form.error_messages[msg]}")
                
                response = {
                            "msg": render_to_string(
                                "static_html/messages.html",
                                {
                                    "messages": messages.get_messages(request),
                                },
                            ),
                        }
                        
            res =  HttpResponse(
                json.dumps(response),
                content_type="application/json",
            )
            res.status_code = 218
        
            return res
        else:
            for msg in form.error_messages:
                messages.error(request, f"{msg.upper()}: {form.error_messages[msg]}")
                
            return error_msg_response(request)
        
    if request.user.is_authenticated:
        return redirect("Main:home_page")
    
    form = LoginForm()
    return render(request,"login.html", context={"form": form})

def register_page(request):
    
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            
            message = render_to_string("activate_account_email.html", {
                "user": user,
                "domain": request.META["HTTP_HOST"],
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
            })
            
            mail_subject = "Activate your Spuiz Account."
            to_email = form.cleaned_data.get("email")
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            
            msg = "Please confirm your email address to complete the registration"
            messages.info(request, msg)
        
            response = HttpResponse(msg)
            response.status_code = 200
            return response
        else:

            errors = json.loads(form.errors.as_json())

            for msg in errors:
                
                error_msg = errors[msg][0]["message"]
                
                if errors[msg][0]["code"] != "":
                    error_msg = errors[msg][0]["code"].upper() + ": " + error_msg
                    
                messages.error(request, error_msg)
                
            return error_msg_response(request)
        
    if request.user.is_authenticated:
        return redirect("Main:home_page")
    
    form = RegistrationForm()
    return render(request, "register.html", context={"form": form})
    
def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        messages.success(request, "You have confirmed your email and have now been logged in")
        return redirect("Main:home_page")
    else:
        return HttpResponse("Activation link is invalid")

def logout_page(request):
    logout(request)
    messages.info(request, "You have been logged out.")
    return HttpResponseRedirect(request.GET.get("next", "/"))

def settings_page(request):
    
    if not request.user.is_authenticated:
        return redirect("Main:home_page")
    
    if request.method == "POST":
        
        user_profile = request.user.user_profile
        
        if "bio" in list(request.POST.keys()):
            
            user_profile.bio = request.POST["bio"]
            user_profile.save()
            
            messages.success(request, "Your biography has been successfully updated.")
        
        elif "avatar" in list(request.FILES.keys()):
            
            user_profile.avatar = request.FILES["avatar"]
            user_profile.save()
            
            messages.success(request, "Your avatar has been successfully updated.")
        
        elif "banner" in list(request.FILES.keys()):
            
            user_profile.banner = request.FILES["banner"]
            user_profile.save()
            
            messages.success(request, "Your banner has been successfully updated.")
                    
        else:
            form = UserEditForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(request, "Your account information has been successfully updated.")
            else:
                # messages.error(request, "An error has occurred while trying to save your account information.")
                errors = json.loads(form.errors.as_json())

                for msg in errors:
                    
                    error_msg = errors[msg][0]["message"]
                    
                    if errors[msg][0]["code"] != "":
                        error_msg = errors[msg][0]["code"].upper() + ": " + error_msg
                        
                    messages.error(request, error_msg)
                 
                data = {
                        "msg": render_to_string(
                            "static_html/messages.html",
                            {
                                "messages": messages.get_messages(request),
                            },
                        )
                    }
                            

Main/templates/activate_account_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,

{{ request.scheme }}://{{ domain }}{% url 'Main:activate' uidb64=uid token=token %}
{% endautoescape %}

Main/templates/create_quiz.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/create_quiz.css' %}">{% endblock %}
{% block title %}Quiz Creator{% endblock %}

{% block content %}
    <section id="create_quiz">
        <form id="quiz-creator" class="quiz-creator" method="post">

            {% csrf_token %}

            <h1 class="form-title">Quiz Creator</h1>

            <div>
                <h2>Quiz Title</h2>
                <input id="quiz_title" name="quiz_title" type="text" placeholder="..." required>
            </div>
            
            <div class="quiz_thumbnail">
                <h2>Quiz Thumbnail</h2>
                <div class="dropbox">
                    <input type="file" name="quiz_thumbnail" id="quiz_thumbnail" accept="image/x-png,image/jpeg" onchange="showPreview(event)" required>
                    <p>Drop image here or click to upload</p>
                    <img style="display: none;" class="thumabnail-preview">
                </div>
                <input type="button" onclick="clearPreview(this)" value="Reset Thumbnail" class="reset-thumbnail-btn">
            </div>

            <div class="options">
                <div>
                    <input type="checkbox" name="media_quiz" id="media_quiz">
                    <label for="media_quiz">Media Quiz</label>
                </div>
    
                <div>
                    <input type="checkbox" name="mcq" id="mcq">
                    <label for="mcq">Multiple Choice</label>
                </div>
            </div>

            <div class="questions-container">
                <h2>Questions</h2>
                <div class="question-container">
                    <h3>Question</h3>
                    <input type="text" name="question_1" placeholder="..." required>
                    <input type="button" name="question_position_1" value="Add more questions" onclick="addQuestion()" class="add-question-btn">
                    <div>
                        <div class="correct-answer-container">
                            <h3>Correct Answers</h3>
                            <div class="correct-answers">
                                <div>
                                    <input type="text" name="correct_answer_1" placeholder="..." required>
                                    <input type="button" name="correct_position_1" value="+" onclick="addAnswer('correct')">
                                </div>
                            </div>
                        </div>
                        <div class="wrong-answer-container">
                            <h3>Wrong Answers</h3>
                            <div class="wrong-answers">
                                <div>
                                    <input type="text" name="wrong_answer_1" placeholder="...">
                                    <input type="button" name="wrong_position_1" value="+" onclick="addAnswer('wrong')">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <button class="create-quiz-btn" type="submit" onclick="validateForm()">Create Quiz</button>
        </form>
    </section>

    <script src="{% static 'assets/js/create_quiz.js' %}"></script>
{% endblock %}

Main/templates/edit_quiz.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/edit_quiz.css' %}">{% endblock %}
{% block title %}Editing {{ quiz.title }}{% endblock %}

{% block content %}
    <section id=edit_quiz>
        <form method="POST" class="card">

            {% csrf_token %}

            <h1>Editing Quiz: {{ quiz.title }}</h1>

            <h2>Quiz Title</h2>
            <input type="text", value="{{ quiz.title }}" name="title">

            <h2>Thumbnail</h2>
            <div class="dropbox">
                <input type="file" name="thumbnail" accept="image/x-png,image/jpeg" class="input-file" onchange="showPreview(event)">
                <p>Drop image here or click to upload</p>
            </div>
            <img src="{{ quiz.thumbnail.url }}" alt="{{ quiz.title }}" class="thumabnail-preview">

            <button class="save" type="submit" onclick="submitForm(event)">Save</button>

        </form>
    </section>

    <script src="{% static 'assets/js/edit_quiz.js' %}"></script>
{% endblock %}

Main/templates/homepage.html
{% extends "index.html" %}
{% load static %}

{% block title %}Home{% endblock %}
{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/homepage.css' %}">{% endblock %}

{% block content %}
    
    <div id="homepage">

        <section id="newest">
            <h2>Newest</h2>
            <div class="quizzes">
                {% for quiz in newest_quizzes %}
                    <div class="quiz">
                        <a href="/{{ quiz.author.user_profile.slug }}/{{quiz.slug}}">
                            <img class="quiz-thumbnail" src="{{ MEAIA_URL }}{{ quiz.thumbnail.url }}" alt="{{ quiz.title }}">
                            <p>{{ quiz.title }}</p>
                        </a>
                        <a class="quiz-author" href="/{{ quiz.author.user_profile.slug }}/">{{ quiz.author.username }}</a>
                    </div>
                {% endfor %}
            </div>
        </section>

        <section id="top_rated">
            <h2>Top Rated</h2>
            <div class="quizzes">
                {% for quiz in top_quizzes %}
                    <div class="quiz">
                        <a href="/{{ quiz.author.user_profile.slug }}/{{quiz.slug}}">
                            <img class="quiz-thumbnail" src="{{ MEAIA_URL }}{{ quiz.thumbnail.url }}" alt="{{ quiz.title }}">
                            <p>{{ quiz.title }}</p>
                        </a>
                        <a class="quiz-author" href="/{{ quiz.author.user_profile.slug }}/">{{ quiz.author.username }}</a>
                    </div>
                {% endfor %}
            </div>
        </section>

    </div>

{% endblock %}

Main/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="UTF-8">
        <link rel="shortcut icon" href="{% static 'assets/img/favicon.ico' %}" type="image/x-icon">
        <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700&display=swap" rel="stylesheet">

        <!-- Load CSS -->
        <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
        <link rel="stylesheet" href="{% static 'assets/css/messages.css' %}">
        <link rel="stylesheet" href="https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        {% block styles %}{% endblock %}
        
        <!-- Load Scripts -->
        <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/1.1.0/marked.min.js"></script>
        <script src="https://kit.fontawesome.com/653eb1b940.js"></script>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta charset="UTF-8">
        <meta name="description" content="A web application for you to create quizzes and let users answer them!">
        <meta name="keywords" content="Quiz, Spuiz, Quiz App, Questions, Answers, MCQ, multiple choice, media">
        <meta name="author" content="Spimy">
        
        <meta property="og:image" content="{% static 'assets/img/favicon.ico' %}">
        <meta property="og:site_name" content="Spuiz">
        <meta property="og:type" content="object">
        <meta property="og:title" content="Spuiz">
        <meta property="og:description" content="A web application for you to create quizzes and let users answer them!">

        <title>Spuiz - {% block title %}{% endblock %}</title>
    </head>
    <body>

        {% include 'static_html/navbar.html' %}
        {% include 'static_html/messages.html' %}

        <div class="content-container">
        {% block content %}
        {% endblock %}
        </div>

        {% comment %} {% include 'static_html/footer.html' %} {% endcomment %}

    </body>
</html>

Main/templates/login.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/login.css' %}">{% endblock %}
{% block title %}Login{% endblock %}

{% block content %}

    <section id="login">
    
        <form class="login-form" method="POST">

            <div class="info-text">
                <h2 class="web-welcome">Welcome to Spuiz</h2>
                A place to create and answer quizzes
            </div>

            {% csrf_token %}
            {{ form.as_p }}

        <button class="login-btn" type="submit">Authenticate</button>

        <a href="/register">
            Create an account
            <i class="fas fa-external-link-alt"></i>
        </a>

        <br>

        <a style="color:lightblue;" href="{% url 'Main:password_reset' %}">Forgot your password?</a>

        </form>

    </section>

    <script src="{% static 'assets/js/login.js' %}"></script>
    
{% endblock %}

Main/templates/notifications.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/notifications.css' %}">{% endblock %}
{% block title %}Notifications{% endblock %}

{% block content %}

    <section id="notifications">
        <div class="container">
            <h1>Notifications</h1>
            <div class="buttons">
                <a href="/notifications/read">Mark all as Read</a>
                <a href="/notifications/delete">Delete all notifications</a>
            </div>

            <div class="card">
                {% if notifications.count > 0 %}
                {% for notification in notifications %}
                <div href="{{ notification.pk }}/read" class="notification {% if notification.read %} read{% endif %}" onclick="toggleRead(this)">
                    <div class="heading">
                        {% if notification.from_user.user_profile.avatar %}
                        <img src="{{ notification.from_user.user_profile.avatar.url }}" alt="{{ notification.from_user.username }}'s avatar">
                        {% else %}
                        <img src="{% static 'assets/img/default.png' %}" alt="{{ notification.from_user.username }}'s avatar">
                        {% endif %}
                        <h2>{{ notification.title }}</h2>
                    </div>
                    <a>{{ notification.message}} </a>
                </div>
                {% endfor %}
                {% else %}
                <h2 style="text-align:center;">You have no notifications...</h2>
                {% endif %}
            </div>
        </div>
    </section>
    <script src="{% static 'assets/js/notifications.js' %}"></script>

{% endblock %}

Main/templates/quiz_complete.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/quiz_complete.css' %}">{% endblock %}
{% block title %}{{ completed.quiz.title }} by {{ completed.quiz.author.username }}{% endblock %}

{% block content %}
    {% with total_score=completed.quiz.questions.all.count %}
        <section id="quiz_result">
            <div class="result">

                <h1 class="title">{{ completed.quiz.title }}</h1>
                <img class="thumbnail" src="{{ MEDIA_URL }}{{ completed.quiz.thumbnail.url }}" alt="{{ completed.quiz.title }}'s thumbnail">

                <div class="score">
                    <h2>Your Score: {{ completed.score }} of {{ total_score }}</h2>
                    <p>Percentage Score: {{ percent }}%</p>
                </div>

                <nav class="rate">
                    <p class="stars">
                    <span>Rating:</span>
                        {% for i in stars %}
                            <span class="fa fa-star star checked"></span>
                        {% endfor %}
                        {% for i in remainder %}
                            <span class="fa fa-star star "></span>
                        {% endfor %}
                    </p>
                    <form class="btns">
                        {% csrf_token %}
                        <button class="updownvote-btn" type="submit" value="upvote">{{ completed.quiz.upvotes.count }} Upvote</button>
                        <button class="updownvote-btn" type="submit" value="downvote">{{ completed.quiz.downvotes.count }} Downvote</button>
                    </form>
                </nav>
                {% if user.is_authenticated %}
                    <a class="profile-btn" href="/{{ user.user_profile.slug }}">Go to Profile</a>
                {% else %}
                    <a class="profile-btn" href="/{{ completed.quiz.author.user_profile.slug }}">Go to Author</a>
                {% endif %}
            </div>
        </section>
        <script src="{% static 'assets/js/quiz_complete.js' %}"></script>
    {% endwith %}
{% endblock %}

Main/templates/quiz_page.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/quiz_page.css' %}">{% endblock %}
{% block title %}{{ quiz.quiz_info.title }} by {{ quiz.quiz_info.author.username }}{% endblock %}

{% block content %}
    
    <section id="quiz">
        <img class="backdrop" src="{{ MEDIA_URL }}{{ quiz.quiz_info.thumbnail.url }}" alt="{{ quiz.quiz_info.title }}">
        
        <form class="quiz-info" method="POST">
            {% csrf_token %}
            {% if quiz.quiz_info.author.user_profile.avatar %}
            <img class="author-avatar" src={{ MEDIA_URL }}{{ quiz.quiz_info.author.user_profile.avatar.url }} alt="{{ quiz.quiz_info.author.username }}">
            {% else %}
            <img class="author-avatar" src="{% static 'assets/img/default.png' %}" alt="{{ quiz.quiz_info.author.username }}">
            {% endif %}
            <div class="quiz-info-wrapper">
                <div class="quiz-info-text">
                    <a href="." class="quiz-title"><h2>{{ quiz.quiz_info.title }}</h2></a>
                    <a href="/{{ quiz.quiz_info.author.user_profile.slug }}" class="quiz-author">by {{ quiz.quiz_info.author.username }}</a>
                </div>
                <div class="quiz-info-btns">
                    <button class="quiz-updownvote" type="submit" value="upvote">{{ quiz.quiz_info.upvotes.count }} Upvote</button>
                    <button class="quiz-updownvote" type="submit" value="downvote">{{ quiz.quiz_info.downvotes.count }} Downvote</button>
                </div>
            </div>
        </form>
        
        <form class="quiz-card" method="POST">

            {% csrf_token %}
            {% for question, answers in quiz.questions.items %}

                <div class="question-card">

                    <div class="wrapper">
                        <p>Question: {{ question }} <span class="required">— this question must be answered</span><p>
                        {% if quiz.quiz_info.media_quiz %}
                            <img src="{{ MEDIA_URL }}{{ question.thumbnail.url }}" alt="{{ question.question }}">
                        {% endif %}
                    </div>

                    {% if quiz.quiz_info.mcq %}
                        <div class="wrapper">
                            <p>Answers: </p>
                            
                            <div class="answer-wrapper">
                            {% for answer in answers %}
                                <label class="answers-label">
                                    <input class="answers" type="radio" name="{{ question.pk }}" value="{{ answer }}" required>
                                    <span>{{ answer }}</span>
                                </label>
                            {% endfor %}
                            </div>
                        </div>
                    {% else %}
                        <div class="answer-wrapper">
                            <p>Answer: </p>
                            <input class="answers" type="text" name="{{ question.pk }}" placeholder="..." required>
                        </div>
                    {% endif %}

                </div>

            {% endfor %}

            <button class="submit-btn" type="submit" value="{{ quiz.quiz_info.mcq | yesno:'yes,no' }}">Submit</button>
        </form>
    </section>

    <script src="{% static 'assets/js/quiz_page.js' %}"></script>

{% endblock %}

Main/templates/register.html
{% extends "index.html" %}
{% load static %}

{% block styles %}<link rel="stylesheet" href="{% static 'assets/css/register.css' %}">{% endblock %}
{% block title %}Register{% endblock %}

{% block content %}
    
    <section id="register">

        <form class="register-form" method="POST">

            <div class="info-text">
                <h2 class="web-welcome">Welcome to Spuiz</h2>
                A place to create and answer quizzes
            </div>

            {% csrf_token %}
            {{ form.as_p }}

        <button class="register-btn" type="submit">Register</button>

        <a href="/login">
            Already have an account? Sign In
            <i class="fas fa-external-link-alt"></i>
        </a>

        </form>

    </section>

    <script src="{% static 'assets/js/register.js' %}"></script>

{% endblock %}